client_config_file: /home/zemi/start/python_code/client_secrets.json

save_credentials: True
save_credentials_backend: file
save_credentials_file: /home/zemi/start/python_code/saved_credentials.json

get_refresh_token: True
